create database dbAtletasOlimpiadas;
use dbAtletasOlimpiadas;
-- drop database dbatletasolimpiadas;
CREATE TABLE estados (
  codEstado int primary key not null auto_increment,
  nomeEstado varchar(255) not null
);

CREATE TABLE cidades (
  codCidade int primary key not null auto_increment,
  nomeCidade varchar(255) not null,
  codEstado int not null,
  foreign key (codEstado) references estados(codEstado)
  
);

CREATE TABLE edicao (
  codedicao int primary key not null auto_increment,
  ano int not null,
  sede varchar(30) not null
);

CREATE TABLE modalidades (
  codModalidade int primary key auto_increment not null,
  nomeModalidade varchar(255) not null
);

CREATE TABLE provas (
  codProva int primary key auto_increment not null,
  nomeProva varchar(255) not null,
  codModalidade int not null,
  foreign key (codModalidade) references modalidades(codModalidade)
);

CREATE TABLE atletas (
  codAtleta int primary key auto_increment,
  nomeAtleta varchar(255) not null,
  dataNascimento varchar(20) not null,
  sexo char(1) not null,
  altura decimal(5,2) not null,
  peso decimal(5,2) not null,
  codCidade int not null,
  codModalidade int not null,
  foreign key (codCidade) references cidades(codCidade),
  foreign key (codModalidade) references modalidades(codModalidade) 
);

CREATE TABLE resultadosatletas (
  codAtletaRes int primary key auto_increment not null,
  codAtleta int,
  codProva int,
  edicao int,
  resultado varchar(255) ,
  medalha varchar(255) ,
  foreign key (codAtleta) references atletas(codAtleta),
  foreign key (codProva) references provas(codProva),
  foreign key (edicao) references edicao(codEdicao)
);

INSERT INTO `estados` (`codEstado`, `nomeEstado`) VALUES
(1, 'Acre'),
(2, 'Alagoas'),
(3, 'Alemanha'),
(4, 'Amapá'),
(5, 'Amazonas'),
(6, 'Argentina'),
(7, 'Armênia'),
(8, 'Austrália'),
(9, 'Bahia'),
(10, 'Bielorussia'),
(11, 'Bélgica'),
(12, 'Ceará'),
(13, 'China'),
(14, 'Colômbia'),
(15, 'Croácia'),
(16, 'Cuba'),
(17, 'Distrito Federal'),
(18, 'EUA'),
(19, 'Espanha'),
(20, 'Espírito Santo'),
(21, 'França'),
(22, 'Goiás'),
(23, 'Grã-Bretanha'),
(24, 'Holanda'),
(25, 'Hungria'),
(26, 'Inglaterra'),
(27, 'Itália'),
(28, 'Japão'),
(29, 'Lituânia'),
(30, 'Maranhão'),
(31, 'Mato Grosso'),
(32, 'Mato Grosso do Sul'),
(33, 'Minas Gerais'),
(34, 'Paraná'),
(35, 'Paraíba'),
(36, 'Pará'),
(37, 'Pernambuco'),
(38, 'Piauí'),
(39, 'Polônia'),
(40, 'Portugal'),
(41, 'Rio Grande do Norte'),
(42, 'Rio Grande do Sul'),
(43, 'Rio de Janeiro'),
(44, 'Rondônia'),
(45, 'Roraima'),
(46, 'Santa Catarina'),
(47, 'Sergipe'),
(48, 'Suiça'),
(49, 'Suécia'),
(50, 'São Paulo'),
(51, 'Sérvia'),
(52, 'Uruguai'),
(53, 'nan');


insert into cidades (nomeCidade,codEstado) values

('?', 50),
('Adamantina', 50),
('Aguaí', 50),
('Americana', 50),
('Amparo', 50),
('Andradina', 50),
('Araraquara', 50),
('Araras', 50),
('Araçatuba', 50),
('Artur Nogueira', 50),
('Arujá', 50),
('Atibaia', 50),
('BASTOS', 50),
('Barra Bonita', 50),
('Barueri', 50),
('Bauru', 50),
('Boa Esperança do Sul', 50),
('Botucatu', 50),
('Brasília', 50),
('CAMPINAS', 50),
('Caieiras', 50),
('Campinas', 50),
('Campo Limpo Paulista', 50),
('Campos do Jordão', 50),
('Capivari', 50),
('Capão Bonito', 50),
('Caraguatatuba', 50),
('Carapicuíba', 50),
('Casa Branca', 50),
('Catanduva', 50),
('Colina', 50),
('Conchal', 50),
('Coronel Macedo', 50),
('Cosmopólis', 50),
('Cotia', 50),
('Cruzeiro', 50),
('Cubatão', 50),
('Descalvado', 50),
('Diadema', 50),
('Dracena', 50),
('Ferraz de Vasconcelos', 50),
('Franca', 50),
('Garça', 50),
('Guararapes', 50),
('Guaratinguetá', 50),
('Guarujá', 50),
('Guarulhos', 50),
('Guaíra', 50),
('ITARIRI', 50),
('ITU', 50),
('Ibirá', 50),
('Ibitinga', 50),
('Iguape', 50),
('Ilha Solteira', 50),
('Ilhabela', 50),
('Indiaporã', 50),
('Ipaussu', 50),
('Itanhaém', 50),
('Itapeva', 50),
('Itatiba', 50),
('Itu', 50),
('Ituverava', 50),
('Jacareí', 50),
('Jandira', 50),
('Jaú', 50),
('Jundiaí', 50),
('Juquiá', 50),
('Leme', 50),
('Lençóis Paulista', 50),
('Limeira', 50),
('Lins', 50),
('Lorena', 50),
('Lucélia', 50),
('Marília', 50),
('Matão', 50),
('Mauá', 50),
('Mococa', 50),
('Mogi das Cruzes', 50),
('Morungaba', 50),
('Nova Odessa', 50),
('Orlândia', 50),
('Osasco', 50),
('Osvaldo Cruz', 50),
('Pacaembu', 50),
('Paraguaçu Paulista', 50),
('Parapuã', 50),
('Pariquera-Açu', 50),
('Patrocinio Paulista', 50),
('Pedregulho', 50),
('Pedro de Toledo', 50),
('Penápolis', 50),
('Peruíbe', 50),
('Pindamonhangaba', 50),
('Piracicaba', 50),
('Piraju', 50),
('Pirassununga', 50),
('Porto Ferreira', 50),
('Potirendaba', 50),
('Praia Grande', 50),
('Presidente Prudente', 50),
('Promissão', 50),
('Quintana', 50),
('Registro', 50),
('Ribeirão Preto', 50),
('Rio Claro', 50),
('Rio de Janeiro', 50),
('Rosárial', 50),
('Rubineia', 50),
('Salto', 50),
('Santa Bárbara d Oeste', 50),
('Santa Maria da Serra', 50),
('Santa Rita do Passa Quatro', 50),
('Santo André', 50),
('Santo Antônio de Posse', 50),
('Santos', 50),
('Saudades', 50),
('Sertãozinho', 50),
('Sorocaba', 50),
('Sumaré', 50),
('Suzano', 50),
('São Bernardo do Campo', 50),
('São Caetano do Sul', 50),
('São Carlos', 50),
('São Joaquim da Barra', 50),
('São José do Rio Preto', 50),
('São José dos Campos', 50),
('São João da Boa Vista', 50),
('São Manuel', 50),
('São Paulo', 50),
('São Roque', 50),
('São Sebastião', 50),
('São Vicente', 50),
('Taubaté', 50),
('Tietê', 50),
('Tupi Paulista', 50),
('Tupã', 50),
('Ubatuba', 50),
('Valinhos', 50),
('Vinhedo', 50),
('Vista Alegre do Alto', 50),
('Votorantim', 50),
('Álvares Machado', 50);

insert into modalidades(nomeModalidade) values ("Ginástica artística");

insert into provas(nomeProva,codModalidade) values
("Argolas Masculino",1),  
("Barra Fixa",1),  
("Barra Fixa Masculino",1),  
("Barras Assimétricas Feminino",1),  
("Barras Paralelas Masculino",1),  
("Cavalo com Alças Masculino",1),  
("Equipes Feminino",1),  
("Equipes Masculino",1),  
("Individual All-Around Feminino",1),  
("Individual All-Around Masculino",1),  
("Individual Geral Feminino",1),  
("Individual Geral Masculino",1),  
("Salto sobre a mesa Feminino",1),  
("Salto sobre a mesa Masculino",1),  
("Solo Feminino",1),  
("Solo Masculino",1),
("Trave de Equilibrio Feminino",1);


INSERT INTO atletas (nomeAtleta, dataNascimento, sexo, altura, peso, codCidade, codModalidade)
VALUES ('Rebeca Rodrigues de Andrade', '1999-05-08', 'F', 1.51, 46, 1, 1);

INSERT INTO edicao (ano, sede) VALUES
(1900, 'Paris'),
(1920, 'Antuérpia'),
(1924, 'Paris'),
(1932, 'Los Angeles'),
(1936, 'Berlim'),
(1948, 'Londres'),
(1952, 'Helsinque'),
(1956, 'Melbourne'),
(1960, 'Roma'),
(1964, 'Tóquio'),
(1968, 'Cidade do México'),
(1972, 'Munique'),
(1976, 'Montreal'),
(1980, 'Moscou'),
(1984, 'Los Angeles'),
(1988, 'Seul'),
(1992, 'Barcelona'),
(1996, 'Atlanta'),
(2000, 'Sydney'),
(2004, 'Atenas'),
(2008, 'Pequim'),
(2012, 'Londres'),
(2016, 'Rio de Janeiro'),
(2020, 'Tóquio'),
(2024, 'Paris'),
(2028, 'Los Angeles'),
(2032, 'Brisbane')



